<?php
/**
 * @title    Home
 * @section  home
 * @abstract The KiriBuild end-to-end fixture home page.
 * @stats    _stats.json
 */
?>
<h1><?php echo $project; ?></h1>
<p><?php echo $tagline; ?></p>
<p>Built by {{built-by}}.</p>

<uppercase>generated</uppercase>

<img asset="cover.png" width="80" alt="autogenerated thumbnail">

<ul class="metrics">
    <?php foreach ($stats->metrics as $m): ?>
        <li><?php echo $m->label; ?>: <strong><?php echo $m->value; ?></strong></li>
    <?php endforeach; ?>
</ul>

<markdown>
## From Markdown

- A list item
- Another one
</markdown>

<p><a href="<?php echo $relroot; ?>about/">About</a></p>
